### PR TITLE
Fix for uploading images.

### LINKED ISSUE #444: Uploading images doesn't work
## 📝 Provide detailed reproduction steps (if any)

1. Drop/paste an image into the content
2. It's visible while being uploaded
3. But then the image stays in the content (as an element) but the src is broken
4. After saving the content all's fine, though

It's a weird issue because when I inspect the DOM in step 3, I copy the URL and try to see it, it gives me 404.

But then, when I save the content or switches to the GitHub's native preview mode, it works.

So, unfortunately, it seems that GH is delaying generating the asset until it's really needed.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pszczesniak**
To get correct url we need to do one more fetch (like GitHub does).

Closes #444.

### CODE REVIEW

File: src/app/plugins/githubuploadadapter.js [hunk 1]
```diff
@@ -103,8 +103,32 @@ export class Adapter {
 						// Step 2: the real upload takes place this time to Amazon S3 servers,
 						// using information returned from Step 1.
 
-						// The final URL of the file is already known, even before the upload. We save it here.
-						returnUrl = response.asset.href;
+						const assetUrl = typeof response.asset_upload_url === 'string' ? response.asset_upload_url : null;
```
Comment (mlewand) [inline src/app/plugins/githubuploadadapter.js:106]: We need a comment in the code explaining why is this done in a first place. Otherwise we won't understand this in a month from now.

File: src/app/plugins/githubuploadadapter.js [hunk 2]
```diff
@@ -103,8 +103,32 @@ export class Adapter {
...
+
+						if ( !( assetUrl && authenticityToken ) ) {
+							return;
+						}
+
+						const form = new FormData();
+
+						form.append( 'authenticity_token', authenticityToken );
+
+						fetch( assetUrl, {
```
Comment (mlewand) [inline src/app/plugins/githubuploadadapter.js:118]: Am I right that this request should be send **after** the upload is complete?

Note that uploading is done in this line:

[https://github.com/ckeditor/github-writer/blob/4db90dd71dc58757feac652d439e519c085b4617/src/app/plugins/githubuploadadapter.js#L150](https://github.com/ckeditor/github-writer/blob/4db90dd71dc58757feac652d439e519c085b4617/src/app/plugins/githubuploadadapter.js#L150)

File: src/app/plugins/githubuploadadapter.js [hunk 3]
```diff
@@ -103,8 +103,32 @@ export class Adapter {
...
+							credentials: 'same-origin',
+							headers: {
+								Accept: 'application/json',
+								'X-Requested-With': 'XMLHttpRequest'
+							}
+						} )
+							.then( response => response.json() )
+							.then( response => {
+								// The final URL of the file is already known, even before the upload. We save it here.
+								returnUrl = response.href;
```
Comment (mlewand) [inline src/app/plugins/githubuploadadapter.js:130]: This is where the promise ([constructed in this line](https://github.com/ckeditor/github-writer/blob/4db90dd71dc58757feac652d439e519c085b4617/src/app/plugins/githubuploadadapter.js#L102)) should resolve.

It should resolve with passing the `response.href` so there will be no need for the [globalish variable `returnUrl`](https://github.com/ckeditor/github-writer/blob/4db90dd71dc58757feac652d439e519c085b4617/src/app/plugins/githubuploadadapter.js#L56).

File: src/app/plugins/githubuploadadapter.js (hunk 1 above)
Comment (mlewand) [reply src/app/plugins/githubuploadadapter.js:106]: It makes a perfect sense to wrap this new code into a helper function with a good name, like `sendAssetRequest` or `requestAssetConfirmation`.

**Review by mlewand — CHANGES_REQUESTED** [review]
I have serious doubt in regard to order of asynchronous code here.

**Comment by dufipl** [comment]
## Cannot add a comment with an image on Firefox
### Steps
1. Add image to issue comment on Firefox
2. Press the "Comment" button

### Result
Nothing happens.

**Comment by dufipl** [comment]
## "TypeError: /upload/assets/<number> is not a valid URL" error in the console while uploading an image of Firefox
### Steps
1. Add image to issue/comment on Firefox

### Result
`TypeError: /upload/assets/<number> is not a valid URL` error in the console.

**Comment by charlttsie** [comment]
## Image is not visible after submitting an issue on Firefox
### Steps
1. Add an image to an issue on Firefox
2. Press the "Submit new issue" button

### Result
The image is not visible in the issue description

**Comment by pszczesniak** [comment]
https://github.com/ckeditor/github-writer/pull/450#issuecomment-1580669679 Fixed in https://github.com/ckeditor/github-writer/commit/e10de92c8c0a87d647941e858b7a571b457ca5be.

File: src/app/plugins/githubuploadadapter.js [hunk 4]
```diff
@@ -129,10 +129,14 @@ export class Adapter {
 						this._sendRequest( data );
 					} ) )
 					.then( ( /* { file, response } */ ) => {
-						// Upload concluded! Simply send the file URL back, according to CKEditor specs.
-						return {
-							default: returnUrl
-						};
+						// Step 3: Retrieve the final uploaded asset URL using response data gathered on Step 1.
+						return this.sendAssetRequest( assetResponse )
```
Comment (mlewand) [inline src/app/plugins/githubuploadadapter.js:133]: Let the `sendAssetRequest` be a private method, just like the others around here. No need to expose it.

File: src/app/plugins/githubuploadadapter.js [hunk 5]
```diff
@@ -129,10 +129,14 @@ export class Adapter {
 						this._sendRequest( data );
 					} ) )
 					.then( ( /* { file, response } */ ) => {
```
Comment (mlewand) [inline src/app/plugins/githubuploadadapter.js:131]: Since handling here became very messy I took the liberty to extract all of these 3 promise handlers to 3 separate functions with decent names so that it's more obvious for people what they do, and so that they became somewhat more separated.

**Review by mlewand — CHANGES_REQUESTED** [review]
There are still some code to be polished.

We'll do a live-review and run though these items.

**Review by mlewand — APPROVED** [review]
Fixes added in 8e1c3b1.

Code looks good, let's wait for R+ from the QA team. Once we have it we can merge it straight away and release the fixed version!

**Comment by dufipl** [comment]
## No image preview when adding inline comment during code review
### Steps
1. Open the inline code comment editor within a PR
2. Add an image to the comment

### Result
No preview, but after a while it is possible to send comments and image show up:

https://github.com/ckeditor/github-writer/assets/32898551/4e4ee5cc-8d37-423a-95da-0797fc8b022f

**Comment by pszczesniak** [comment]
https://github.com/ckeditor/github-writer/pull/450#issuecomment-1584553496 fixed in https://github.com/ckeditor/github-writer/commit/7166deee8f33f86d33cb02538ac49e21eff061ab.
